kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: zee.aether.configuration.module.default.genesis
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.zee","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.zee.git","filePath":"/.defaults/module_configurations/module_aether/tree/root/t0/module_configurations/module_aether/genesis/genesis_default.yaml","tenantCode":"zee"}'
spec:
  metadata:
    id: aether.configuration.module.bankzee_us.genesis
    name: Bank Zee US Premium Genesis
    description: Master identity and currency configuration for Bank Zee US Affluent segment.
    requester:
      module: aether
      moduleVersion: 0.0.1
    tenantId: '802156'
    tenantCode: zee
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {"additionalProperties":false,"properties":{"ifiCode":{"type":"string"},"ifiCurrency":{"type":"string"},"ifiLogoUrls":{"items":{"properties":{"logoSize":{"type":"string"},"logoTheme":{"type":"string"},"logoUrl":{"type":"string"}},"required":["logoTheme","logoSize","logoUrl"],"type":"object"},"type":"array"},"ifiName":{"type":"string"},"status":{"type":"string"},"tenantId":{"type":"number"}},"required":["tenantId","ifiName","ifiCode","ifiLogoUrls","ifiCurrency","status"],"type":"object"}
    key: key
    isEncrypted: false
    useVault: false
    value:
      ifiCode: BZ_US_NAT_001    # Unique bank identification code, no 2 banks should have same code 
      ifiName: Bank ZEE USA
      status: ACTIVE  # weather the bank is ACTIVE or not 
      tenantId: 802156    # it is a unique id that is used to identify the tenant from whihch the payment is happened .
      ifiLogoUrls:
        - logoSize: SMALL
          logoTheme: LIGHT
          logoUrl: https://assets.bankzee.com/branding/v1/US_SMALL_LIGHT.svg
        - logoSize: BIG
          logoTheme: DARK
          logoUrl: https://assets.bankzee.com/branding/v1/US_PREMIUM_DARK.png
        - logoSize: BIG
          logoTheme: LIGHT
          logoUrl: https://assets.bankzee.com/branding/v1/US_STATEMENT_LOGO.png
      
  viewConfig:
    angelosSchema:
      view:
        entityId: angelos.aether.genesis
    displayName: Bank Zee US Premium Genesis
