kind: Feature
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: zee.aether.feature.feature-flag-configs
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.zee","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.zee.git","filePath":"module_configurations/module_aether/Feature/feature_feature-flag-configs.yaml","tenantCode":"zee"}'
spec:
  metadata:
    id: aether.feature.feature-flag-configs
    name: featureFlagConfigs
    description: Sample Feature
    requester:
      module: aether
      moduleVersion: 0.0.1
    tenantId: '802156'
    tenantCode: zee
  state: ENABLED
  configParams:
    - key: audit.enabled
      value: 'true'
      isEncrypted: false
      useVault: false
    - key: isCardHolderProfileRequired
      value: 'true'
      isEncrypted: false
      useVault: false
    - key: isBmsEnabled
      value: 'true'
      isEncrypted: false
      useVault: false
    - key: setLimitsViaFormFactorManager
      value: 'false'
      isEncrypted: false
      useVault: false
    - key: isAliasDisabledForBundleStatus
      value: 'true'
      isEncrypted: false
      useVault: false
    - key: fallbackForLuminosBundleStatus
      value: 'true'
      isEncrypted: false
      useVault: false
  viewConfig:
    displayName: feature-flags
