kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: zee.aether.productbundle.bankzee.premium
  labels:
    rrsd.zetaapps.in/day: day-one
  
  metadata:
    id: aether.configuration.bankzee.premium.bundle.product
    name: Bank Zee Black - Ultra Affluent Bundle
    description: Bundle consisting of Bank Zee Premium Credit Card, Bank Zee Premium Account and Bank Zee Premium Rewards
    requester:
      module: aether
      moduleVersion: 0.0.1
    tenantId: '802156'
    tenantCode: zee
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {"type":"object"}
    key: key
    isEncrypted: false
    useVault: false
    value:
      code: PRDUS009979
      name: Bank Zee Black Infinite
      description: Premium Credit with 5x Travel Rewards and $300 Travel Credit
      # --- LINKING CODES START HERE ---
      # This links this commercial bundle to the "Rule Book" (File 1)
      bundleDefinitionCode: BZPCC_STATUS_MAP 
      
      # --- LINKING CODES END HERE ---
      issuanceStartDate: 2026-01-01T00:00:00.000-05:00 # US Eastern Time
      issuanceEndDate: 2099-12-31T23:59:59.000-05:00
      status: active

      marketingAttributes:
        metalWeight: "18g"
        primaryPerk: "Unlimited Priority Pass"
        annualFee: "$500" # Annual Membership Fee 
        initiationFee: "$200" # One-time startup cost 
        aprFormula: "Prime + 21.99%" # Variable APR logic 
      componentProducts:
        - alias: CREDIT_LEDGER    # Accounting engine tracks balances and transactions
          product:
            externalProductCode: BZ_CREDIT_PROD_01
        - alias: REWARDS_CATALOG  # Points engine
          product:
            externalProductCode: BZ_ULTIMATE_REWARDS
        - alias: MASTERCARD_INFINITE_NETWORK  #that connects the card to merchants
          product:
            externalProductCode: BZ_MASTERCARD_INF_CORE
        - alias: FEE_PLAN
          product:
            externalProductCode: BZ_AFFLUENT_FEES_V1
        - alias: LOAN_CONVERSION_ENGINE               # "Buy Now, Pay Later" feature
          product:
            externalProductCode: ELCUS008005
