apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyLateFeePolicy
metadata:
  name: lsg.ruby.rubylatefeepolicy.1001
spec:
  metadata:
    id: ruby.rubylatefeepolicy.1001
    name: 1001 Ruby Late Fee Policy
    description: 1001 Ruby Late Fee Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Late Fee Policy
  code: LPFUS001001
  description: Ruby Late Fee Policy
  modelParameters:
    amountType: FIXED
    repeatedOccurrence:
      maxAmount: 5000
      baseAmount: 3900
    firstOccurenceAmount:
      maxAmount: 4000
      baseAmount: 2900
    repeatOccurrenceWindow:
      type: CYCLES
      count: '6'
    balanceNotSubjectedToThisFee:
      - LateFeeUnbilled
  precedenceCode: ZZ0025
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2999-01-01T23:09:01.795+07:00'
  templateCode: us-credit
