apiVersion: rrsd.zetaapps.in/v1alpha1
kind: EmeraldClosurePolicy
metadata:
  name: lsg.emerald.emeraldclosurepolicy.8005
spec:
  metadata:
    id: emerald.emeraldclosurepolicy.8005
    name: Emerald Closure Policy
    description: Emerald Closure Policy
    requester:
      module: emerald-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2010-04-01T00:00:00.000+05:30'
  validTill: '2999-12-31T00:00:00.000+05:30'
  name: EMI CLOSURE Policy
  description: Credit Card EMI CLOSURE Policy
  code: ECPUS008005
  allowCancellation: true
  coolingPeriodForCancellation: 90
  allowPreClosure: true
  preClosureLockIn: 0
  autoPreClosureThresholdPercentage: 89.99
  includeCatchUpInterest: true
  templateCode: us-credit
