apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyLoanConversionFeePolicy
metadata:
  name: lsg.ruby.loanconversionfeepolicy.8001
spec:
  code: LCFUS008001
  description: loan conversion fee policy changed
  metadata:
    description: 8001 loan fee policy
    id: ruby.loanconversionfeepolicy.8001
    name: 8001 conversion fee policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantCode: lsg
    tenantId: '600309'
  modelParameters:
    isDerivedChargeComponentNotRequired: true
  name: loan conversion fee policy
  templateCode: us-credit
  validFrom: '2010-04-01T00:00:00.000+05:30'
  validTill: '2999-12-31T00:00:00.000+05:30'
